### PR TITLE
add check for attrs attribute in MyHTMLParser

### LINKED ISSUE #10: Process crashed with `AttributeError: 'MyHTMLParser' object has no attribute 'attrs'`
The program seems to be downloading attached images or something.

This is a Ubuntu 20.10 desktop, run by Python 3.8.6 in a Python venv.

## Traceback _(most recent call last)_

- #### File "/venv/lib/python3.8/site-packages/flask/app.py", line _2464_, in `__call__`
        
        
        
        def __call__(self, environ, start_response):
        
        """The WSGI server calls the Flask application object as the
        
        WSGI application. This calls :meth:`wsgi_app` which can be
        
        wrapped to applying middleware."""
        
        return self.wsgi_app(environ, start_response)
        
        
        
        def __repr__(self):
        
        return "&lt;%s %r&gt;" % (self.__class__.__name__, self.name)
        
- #### File "/venv/lib/python3.8/site-packages/flask/app.py", line _2450_, in `wsgi_app`
        
        try:
        
        ctx.push()
        
        response = self.full_dispatch_request()
        
        except Exception as e:
        
        error = e
        
        response = self.handle_exception(e)
        
        except:  # noqa: B001
        
        error = sys.exc_info()[1]
        
        raise
        
        return response(environ, start_response)
        
        finally:
        
- #### File "/venv/lib/python3.8/site-packages/flask/app.py", line _1867_, in `handle_exception`
        
        # if we want to repropagate the exception, we can attempt to
        
        # raise it with the whole traceback in case we can do that
        
        # (the function was actually called from the except part)
        
        # otherwise, we just raise the error again
        
        if exc_value is e:
        
        reraise(exc_type, exc_value, tb)
        
        else:
        
        raise e
        
        
        
        self.log_exception((exc_type, exc_value, tb))
        
        server_error = InternalServerError()
        
- #### File "/venv/lib/python3.8/site-packages/flask/_compat.py", line _39_, in `reraise`
        
        import collections.abc as collections_abc
        
        
        
        def reraise(tp, value, tb=None):
        
        if value.__traceback__ is not tb:
        
        raise value.with_traceback(tb)
        
        raise value
        
        
        
        implements_to_string = _identity
        
        
        
        ![Open an interactive python shell in this frame][img41]else:
        
        iterkeys = lambda d: d.iterkeys()
        
- #### File "/venv/lib/python3.8/site-packages/flask/app.py", line _2447_, in `wsgi_app`
        
        ctx = self.request_context(environ)
        
        error = None
        
        try:
        
        try:
        
        ctx.push()
        
        response = self.full_dispatch_request()
        
        except Exception as e:
        
        error = e
        
        response = self.handle_exception(e)
        
        except:  # noqa: B001
        
        error = sys.exc_info()[1]
        
- #### File "/venv/lib/python3.8/site-packages/flask/app.py", line _1952_, in `full_dispatch_request`
        
        request_started.send(self)
        
        rv = self.preprocess_request()
        
        if rv is None:
        
        rv = self.dispatch_request()
        
        except Exception as e:
        
        rv = self.handle_user_exception(e)
        
        return self.finalize_request(rv)
        
        
        
        def finalize_request(self, rv, from_error_handler=False):
        
        """Given the return value from a view function this finalizes
        
        the request by converting it into a response and invoking the
        
- #### File "/venv/lib/python3.8/site-packages/flask/app.py", line _1821_, in `handle_user_exception`
        
        return self.handle_http_exception(e)
        
        
        
        handler = self._find_error_handler(e)
        
        
        
        if handler is None:
        
        reraise(exc_type, exc_value, tb)
        
        return handler(e)
        
        
        
        def handle_exception(self, e):
        
        """Handle an exception that did not have an error handler
        
        associated with it, or that was raised from an error handler.
        
- #### File "/venv/lib/python3.8/site-packages/flask/_compat.py", line _39_, in `reraise`
        
        import collections.abc as collections_abc
        
        
        
        def reraise(tp, value, tb=None):
        
        if value.__traceback__ is not tb:
        
        raise value.with_traceback(tb)
        
        raise value
        
        
        
        implements_to_string = _identity
        
        
        
        ![Open an interactive python shell in this frame][img85]else:
        
        iterkeys = lambda d: d.iterkeys()
        
- #### File "/venv/lib/python3.8/site-packages/flask/app.py", line _1950_, in `full_dispatch_request`
        
        self.try_trigger_before_first_request_functions()
        
        try:
        
        request_started.send(self)
        
        rv = self.preprocess_request()
        
        if rv is None:
        
        rv = self.dispatch_request()
        
        except Exception as e:
        
        rv = self.handle_user_exception(e)
        
        return self.finalize_request(rv)
        
        
        
        def finalize_request(self, rv, from_error_handler=False):
        
- #### File "/venv/lib/python3.8/site-packages/flask/app.py", line _1936_, in `dispatch_request`
        
        getattr(rule, "provide_automatic_options", False)
        
        and req.method == "OPTIONS"
        
        ):
        
        return self.make_default_options_response()
        
        # otherwise dispatch to the handler for that endpoint
        
        return self.view_functions[rule.endpoint](**req.view_args)
        
        
        
        def full_dispatch_request(self):
        
        """Dispatches the request and on top of that performs request
        
        pre and postprocessing as well as HTTP exception catching and
        
        error handling.
        
- #### File "/onenote_export.py", line _236_, in `main_logic`
        
        ![Open an interactive python shell in this frame][img109]def main_logic():
        
        code = flask.request.args['code']
        
        token = application.acquire_token_by_authorization_code(code, scopes=scopes,
        
        redirect_uri=redirect_uri)
        
        graph_client = OAuth2Session(token=token)
        
        download_notebooks(graph_client, app.config['output_path'], app.config['select_path'], indent=0)
        
        print("Done!")
        
        return flask.render_template_string('&lt;html&gt;'
        
        '&lt;head&gt;&lt;title&gt;Done&lt;/title&gt;&lt;/head&gt;'
        
        '&lt;body&gt;&lt;p1&gt;&lt;b&gt;Done&lt;/b&gt;&lt;/p1&gt;&lt;/body&gt;'
        
        '&lt;/html&gt;')
        
- #### File "/onenote_export.py", line _175_, in `download_notebooks`
        
        nb_name = nb["displayName"]
        
        indent_print(indent, f'Opening notebook {nb_name}')
        
        sections = get_json(graph_client, nb['sectionsUrl'])
        
        section_groups = get_json(graph_client, nb['sectionGroupsUrl'])
        
        indent_print(indent + 1, f'Got {len(sections)} sections and {len(section_groups)} section groups.')
        
        download_sections(graph_client, sections, path / nb_name, select, indent=indent + 1)
        
        download_section_groups(graph_client, section_groups, path / nb_name, select, indent=indent + 1)
        
        
        
        
        
        ![Open an interactive python shell in this frame][img129]def download_section_groups(graph_client, section_groups, path, select=None, indent=0):
        
        section_groups, select = filter_items(section_groups, select, 'section groups', indent)
        
- #### File "/onenote_export.py", line _196_, in `download_sections`
        
        for sec in sections:
        
        sec_name = sec["displayName"]
        
        indent_print(indent, f'Opening section {sec_name}')
        
        pages = get_json(graph_client, sec['pagesUrl'] + '?pagelevel=true')
        
        indent_print(indent + 1, f'Got {len(pages)} pages.')
        
        download_pages(graph_client, pages, path / sec_name, select, indent=indent + 1)
        
        
        
        
        
        ![Open an interactive python shell in this frame][img139]def download_pages(graph_client, pages, path, select=None, indent=0):
        
        pages, select = filter_items(pages, select, 'pages', indent)
        
        pages = sorted([(page['order'], page) for page in pages])
        
- #### File "/onenote_export.py", line _212_, in `download_pages`
        
        if level == 0:
        
        page_dir = path / page_title
        
        else:
        
        page_dir = level_dirs[level - 1] / page_title
        
        level_dirs[level] = page_dir
        
        download_page(graph_client, page['contentUrl'], page_dir, indent=indent + 1)
        
        
        
        
        
        ![Open an interactive python shell in this frame][img150]def download_page(graph_client, page_url, path, indent=0):
        
        out_html = path / 'main.html'
        
        if out_html.exists():
        
- #### File "/onenote_export.py", line _225_, in `download_page`
        
        path.mkdir(parents=True, exist_ok=True)
        
        response = get(graph_client, page_url, indent=indent)
        
        if response is not None:
        
        content = response.text
        
        indent_print(indent, f'Got content of length {len(content)}')
        
        content = download_attachments(graph_client, content, path, indent=indent)
        
        with open(out_html, "w", encoding='utf-8') as f:
        
        f.write(content)
        
        
        
        
        
        ![Open an interactive python shell in this frame][img163]@app.route("/getToken")
        
- #### File "/onenote_export.py", line _146_, in `download_attachments`
        
        with open(attachment_dir / file_name, "wb") as f:
        
        f.write(data)
        
        props['data'] = "attachments/" + file_name
        
        return generate_html('object', props)
        
        
        
        content = re.sub(r"&lt;img .*?\\/&gt;", download_image, content, flags=re.DOTALL)
        
        content = re.sub(r"&lt;object .*?\\/&gt;", download_attachment, content, flags=re.DOTALL)
        
        return content
        
        
        
        
        
        ![Open an interactive python shell in this frame][img174]def indent_print(depth, text):
        
- #### File "/usr/lib/python3.8/re.py", line _210_, in `sub`
        
        non-overlapping occurrences of the pattern in string by the
        
        replacement repl.  repl can be either a string or a callable;
        
        if a string, backslash escapes in it are processed.  If it is
        
        a callable, it's passed the Match object and must return
        
        a replacement string to be used."""
        
        return _compile(pattern, flags).sub(repl, string, count)
        
        
        
        ![Open an interactive python shell in this frame][img182]def subn(pattern, repl, string, count=0, flags=0):
        
        """Return a 2-tuple containing (new_string, number).
        
        new_string is the string obtained by replacing the leftmost
        
        non-overlapping occurrences of the pattern in the source
        
- #### File "/onenote_export.py", line _108_, in `download_image`
        
        def download_image(tag_match):
        
        # &lt;img width="843" height="218.5" src="..." data-src-type="image/png" data-fullres-src="..."
        
        # data-fullres-src-type="image/png" /&gt;
        
        parser = MyHTMLParser()
        
        parser.feed(tag_match[0])
        
        props = parser.attrs
        
        image_url = props.get('data-fullres-src', props['src'])
        
        image_type = props.get('data-fullres-src-type', props['data-src-type']).split("/")[-1]
        
        file_name = ''.join(random.choice(string.ascii_lowercase) for _ in range(10)) + '.' + image_type
        
        req = get(graph_client, image_url, indent=indent)
        
        if req is None:
        

> AttributeError: 'MyHTMLParser' object has no attribute 'attrs'

### PR DESCRIPTION
**Pull request by thfrei**
Add a check for parser.attrs

fixes #10

### CODE REVIEW

**Comment by danmou** [comment]
Thanks for the PR! However I don't think this is the right solution. It seems like the HTML parser doesn't detect a start tag. Could you add a print for `tag_match[0]` and let me know what value it has in the case that fails?

**Comment by thfrei** [comment]
Thank you Danmou for your incredibly fast response, and sorry for my delay. You are probably right, I just hacked together something, so that it would work.

I think I have to abandon using the api, since I do not get any of my hand-drawings out of it. I think I'll stick to something like `.mht` export and then extracting the base64-images.

**Comment by maphew** [comment]
Here's results of my `tag_match[0]` print, commit b098dc6e553d64725aa46b19ae352c20f5099d75
```
...snip...
    Opening page 7 Fossil CMS
      HTML file already exists; skipping this page
    Opening page 8 Fossil learning TH1
      Got content of length 19954
parser.feed tag_match: <img alt="THI:
global State flags
global State user
Run THI
&lt;Base href=&quot; $baseurl/$current_page
&lt;meta
&lt;meta http—egui•F-&quot;Content—security—policy&quot; csp&quot; />
127.0.0.1 - - [04/Jan/2022 07:48:47] "GET /getToken?code=M.R3_BAY.225081db-b1a8-f945-ac69-3ee570dcadd4&state=a6efcfda-9d5f-4e28-98dd-93b766dd6b55 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\ProgramData\scoop\apps\miniconda3\4.10.3\Lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\ProgramData\scoop\apps\miniconda3\4.10.3\Lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\ProgramData\scoop\apps\miniconda3\4.10.3\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\scoop\apps\miniconda3\4.10.3\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request

    rv = self.handle_user_exception(e)
  File "C:\ProgramData\scoop\apps\miniconda3\4.10.3\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request

    rv = self.dispatch_request()
  File "C:\ProgramData\scoop\apps\miniconda3\4.10.3\Lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Matt\code\onenote_export\onenote_export.py", line 240, in main_logic
    download_notebooks(graph_client, app.config['output_path'], app.config['select_path'], indent=0)
  File "C:\Users\Matt\code\onenote_export\onenote_export.py", line 179, in download_notebooks
    download_sections(graph_client, sections, path / nb_name, select, indent=indent + 1)
  File "C:\Users\Matt\code\onenote_export\onenote_export.py", line 200, in download_sections
    download_pages(graph_client, pages, path / sec_name, select, indent=indent + 1)
  File "C:\Users\Matt\code\onenote_export\onenote_export.py", line 216, in download_pages
    download_page(graph_client, page['contentUrl'], page_dir, indent=indent + 1)
  File "C:\Users\Matt\code\onenote_export\onenote_export.py", line 229, in download_page
    content = download_attachments(graph_client, content, path, indent=indent)
  File "C:\Users\Matt\code\onenote_export\onenote_export.py", line 150, in download_attachments
    content = re.sub(r"<img .*?\/>", download_image, content, flags=re.DOTALL)
  File "C:\ProgramData\scoop\apps\miniconda3\4.10.3\Lib\re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Users\Matt\code\onenote_export\onenote_export.py", line 112, in download_image
    props = parser.attrs
AttributeError: 'MyHTMLParser' object has no attribute 'attrs'
```

**Comment by maphew** [comment]
Here's a screenshot of the portion of the page it seems to be having trouble with. It's two images embedded in a table

image

**Comment by maphew** [comment]
the complete tag match text is:
```
<img alt="THI:
global State flags
global State user
Run THI
&lt;Base href=&quot; $baseurl/$current_page
&lt;meta
&lt;meta http—egui•F-&quot;Content—security—policy&quot; csp&quot; />
```

(updated the debug statement to `if debug: print(f"parser.feed tag_match: '''{tag_match[0]}''' ")` to make it easier to see )

**Pull request closed without merging**
